### ISSUE TITLE
clugh

### ISSUE THREAD

**Issue by moien007** [krystalgamer/nta_sources#1]
Well, I don't really care but I'm a bit curious to know why you're saying  "A leak that was given to me" while you got it from [this UC post](https://www.unknowncheats.me/forum/call-of-duty-modern-warfare-3-a/174127-fourdeltaone-source-code-iw4m-iw5m-t5m-alterops-libnp.html)? This  is not the only place where you used that sentence, [here's another](https://www.unknowncheats.me/forum/1825108-post2.html).

**Comment by krystalgamer** [comment]
Yes you gave it to me  through PMs. When you originally made the post you couldn't post the full 4D1 so I asked  for the full sources.

Don't know why you're opening this issue, the only reason I made this was due to preservation.

**Comment by moien007** [comment]
Ahh, you are right, I forgot that. accept my apologies if I sound offensive.
Do you have discord or something? :)
